### ISSUE TITLE
Feature request: Configurable chance for the mod to trigger each day ingame

### ISSUE THREAD

**Issue by Index154** [TheBlackEntity/LethalCompany-LetsGoDeeper#1]
I think it would be great if there was a configurable chance for the mod to change the door behavior on any given moon.

For example if the user set the "activation chance" to 10% it would make it so 9/10 moons would still let you exit through the facility entrance (and enter through the fire exits) as usual, basically "disabling" the mod for those moons and only 10% of the time there would be the extra challenge of having to find a fire exit to leave.

The idea would be to essentially expand on the configs you already have for "Allow Fire Exit Enter" and "Allow Main Entrance Exit" by allowing them to be probabilities instead of booleans. Although I think it would be better to have them both be controlled by one percentage rather than independently.

**Comment by RedSun42** [comment]
On the same optic, would it be possible to have a config setting to let you chose a list of valid moons to apply the mod to? 

I made a modpack where all moons have a theme and I would like one of the moons to have only 1 loot inside worth a lot. There would be no enemies but you can't leave through the main door. the twist would be the mimic door mod. I would have tons of them inside :) 

Thanks!

**Comment by Index154** [comment]
Just realized I worded the title somewhat misleadingly.

Anyway, what RedSun said is a very important point actually. There are modded moons where you can only enter through fire exits under certain circumstances. For example Magic_Wesley's Gratar has two fire exits that connect to each other and are located away from the rest of the map. So if you left through one of these you would be stranded with this mod active. Being able to blacklist moons like this is necessary to keep them playable.

**Comment by Test-Account666** [comment]
Sorry for never making a statement to this...

I personally don't like the idea of having a random chance for this mod.

I think being able to blacklist specific moons would be great though ^^

**Comment by Index154** [comment]
Fair enough! Thanks for the reply

**Comment by Index154** [comment]
I ended up making a mod for this myself. Just in case anyone else still wants a variant with these features: https://github.com/Index154/LC_DoWeNeedToGoDeeper
