### ISSUE TITLE
[Conflict] FeedFish mod incompatible

### ISSUE THREAD

**Issue by CoolLKKPS** [TheBlackEntity/LethalCompany-LetsGoDeeper#2]
@TheBlackEntity https://thunderstore.io/c/lethal-company/p/Yorimor/FeedFish

**Comment by Test-Account666** [comment]
Please attach a log file. 

I can't see a reason why the mods should be incompatible

**Comment by CoolLKKPS** [comment]
so this issue is from maybe 2 weeks ago, and i found ur github recently, so already can't find the log now, but i can tell u how to reproduce

**Comment by CoolLKKPS** [comment]
FeedFish will eat deadbody, and no matter `Only if all bodies found` is true or not, after that Fish eat the body, in `other` player log console will receive an error about `FakeBody` patch

**Comment by CoolLKKPS** [comment]
@TheBlackEntity another issue is from [AutomaticInventoryFixPlugin](https://thunderstore.io/c/lethal-company/p/TestAccount666/AutomaticInventoryFixPlugin)
so if user got `[Info   : Unity Log] grabInvalidated: False` spamming in the log console, they hands will glitched, i know u fixed that, but that cause another issue:
if triggered the fixer u made, they also `Automatic` trigger the vanilla speed glitch which let them being a speed hacker; i sug if they got `[Info   : Unity Log] grabInvalidated: False` spamming on their log console, they will drop all the items and reset their weight to 0 lb; make sure u add additional checker to let the fixer stop if inventory is already empty, to make their weight function back to normal instead to not count any weight that should add, again this is vanilla glitch, weight should update when `grabInvalidated` are set to `true`
and make sure u check out lobbycontrol item_sync function, that actually prevent many cheats and might affect this mod (just in case)

**Comment by Test-Account666** [comment]
> @TheBlackEntity another issue is from [AutomaticInventoryFixPlugin](https://thunderstore.io/c/lethal-company/p/TestAccount666/AutomaticInventoryFixPlugin) so if user got `[Info : Unity Log] grabInvalidated: False` spamming in the log console, they hands will glitched, i know u fixed that, but that cause another issue, if trigger the fixer, they also `Automatic` trigger the speed glitch which let them being a speed hacker, i sug if they trigger this glitch, they will drop all the items and reset weight to 0 lb, make sure u add a checker to let the fixer stop if inventory is already empty, otherwise user will trigger the speed glitch again when they drop the glitched items (since that fixer doesn't design to handle item weight for now), and u might need to check lobbycontrol mod, that mod also have item checker to prevent some cheats

This is quite hard to read tbh 😅 

Can you try to rephrase this?

**Comment by CoolLKKPS** [comment]
@TheBlackEntity updated

**Comment by CoolLKKPS** [comment]
i don't think u really understand, might be a bit hard
