### ISSUE TITLE
[Issue] config sync pls

### ISSUE THREAD

**Issue by CoolLKKPS** [TheBlackEntity/LethalCompany-LetsGoDeeper#3]
@Test-Account666 add config sync to make sure everyone will correctly affect

**Comment by Test-Account666** [comment]
Hello!

I decided against config syncing, as people usually share their modpack via code anyway.

Which means all configs should already be synced. If not, someone probably tried to cheat or didn't download the modpack properly.

Also, adding the networking required for this is quite the pain
